# Oefeningen basis Python

Importeer de volgende bibliotheken: math, numpy en pandas

In [408]:
import numpy as np
import pandas as pd

## Lijsten en tabellen

Maak een list met volgende waarden: 1, 2, 3, 4, 5 en stop deze in de variabele "id"

In [409]:
id = list(range(1, 6))
print(id, type(id))

[1, 2, 3, 4, 5] <class 'list'>


Maak een numpy array met volgende waarden: 15, 18, 11, 17, 20 en stop deze in de variabele "leeftijd"

In [410]:
leeftijd = np.array(range(15, 20))
print(leeftijd, type(leeftijd))

[15 16 17 18 19] <class 'numpy.ndarray'>


Zet de waarden van "leeftijd" om naar een pandas Series en zet het resultaat terug in de variabele "leeftijd".  Verifieer dat het type klopt.

In [411]:
leeftijd = pd.Series(leeftijd)
print(leeftijd, type(leeftijd))

0    15
1    16
2    17
3    18
4    19
dtype: int32 <class 'pandas.core.series.Series'>


Maak een list met volgende waarden: 54.2, 68.1, 41.7, 59.5, 65.4 en stop deze in de variabele "gewicht"

In [412]:
gewicht = [54.2, 68.1, 41.7, 59.5, 65.4]
print(gewicht, type(gewicht))

[54.2, 68.1, 41.7, 59.5, 65.4] <class 'list'>


Maak een numpy array met volgende waarden: 36.5, 37.1, 36.4, 37.2, 36.9 en stop deze in de variabele "temp"

In [413]:
temp = np.array([36.5, 37.1, 36.4, 37.2, 36.9])
print(temp, type(temp))

[36.5 37.1 36.4 37.2 36.9] <class 'numpy.ndarray'>


Zet de array "temp" om naar een list en bewaar het resultaat terug in "temp".  Verfifieer dat het type nu wel degelijk een list is.

In [414]:
temp = temp.tolist()
print(temp, type(temp))

[36.5, 37.1, 36.4, 37.2, 36.9] <class 'list'>


Maak een tabel (data frame) waarin de vorige lijsten de kolommen vormen en stop deze in de variabele "gegevens".  Gebruik voor de namen van de kolommen de namen van de variabelen ("id", "leeftijd", "gewicht" en "temp").

In [415]:
gegevens = pd.DataFrame({'id': id, 'leeftijd': leeftijd, 'gewicht': gewicht, 'temp': temp})
print(gegevens)

   id  leeftijd  gewicht  temp
0   1        15     54.2  36.5
1   2        16     68.1  37.1
2   3        17     41.7  36.4
3   4        18     59.5  37.2
4   5        19     65.4  36.9


Toon de kolomnamen van de tabel

In [416]:
print(gegevens.keys())

Index(['id', 'leeftijd', 'gewicht', 'temp'], dtype='object')


Toon het aantal kolommen

In [417]:
print(gegevens.shape[1])  #print(len(gegevens.columns))

4


Toon de kolom met naam 'temp'

In [418]:
print(gegevens['temp'])  # print(gegevens.temp)

0    36.5
1    37.1
2    36.4
3    37.2
4    36.9
Name: temp, dtype: float64


Toon de 2e kolom uit de tabel zonder de naam te gebruiken

In [419]:
print(gegevens.iloc[:, 1])

0    15
1    16
2    17
3    18
4    19
Name: leeftijd, dtype: int32


Verwijder de derde rij uit de tabel

In [420]:
gegevens.drop(2, inplace=True)

Toon de 3e rij uit de tabel

In [421]:
gegevens.iloc[2]

id           4.0
leeftijd    18.0
gewicht     59.5
temp        37.2
Name: 3, dtype: float64

Toon de 2e en de 4e rij uit de tabel

In [422]:
print(gegevens.iloc[[1, 3]], "\n", gegevens)

   id  leeftijd  gewicht  temp
1   2        16     68.1  37.1
4   5        19     65.4  36.9 
    id  leeftijd  gewicht  temp
0   1        15     54.2  36.5
1   2        16     68.1  37.1
3   4        18     59.5  37.2
4   5        19     65.4  36.9


Toon de 2e tot en met 4e rij uit de tabel

In [423]:
print(gegevens.iloc[1:5], "\n", gegevens)

   id  leeftijd  gewicht  temp
1   2        16     68.1  37.1
3   4        18     59.5  37.2
4   5        19     65.4  36.9 
    id  leeftijd  gewicht  temp
0   1        15     54.2  36.5
1   2        16     68.1  37.1
3   4        18     59.5  37.2
4   5        19     65.4  36.9


Bereken de minimum en maximum leeftijd.  Je kan dit doen door de methoden "min()" en "max()" op te roepen op de kolom.

In [424]:
print("Minimum leeftijd: ", gegevens.leeftijd.min())
print("Maximum leeftijd: ", gegevens.leeftijd.max())

Minimum leeftijd:  15
Maximum leeftijd:  19


Bereken de som van alle gewichten en deel die door het aantal gewichten (bereken dus het gemiddelde gewicht).  Je kan hiervoor de methode "sum()" oproepen op de kolom.  De lengte van de kolom vind je met de functie "len()".
Bemerk dat sum() een methode is die je op een object oproept (de kolom) en len() een functie is die niet aan een object gekoppeld is (vergelijkbaar met een static method in java).  Dit laat zien dat Python een hybride taal is waarin je tegelijk OO en procedureel kan programmeren.
Toon het resultaat met 3 cijfers na de komma.  Hier zie je een hint hoe je dat kan doen:
```python
print("pi is{:10.2f}".format(math.pi))
```

In [425]:
sum = gegevens.gewicht.sum()
quantiy = len(gegevens.gewicht)
x = sum / quantiy
print("Solution: {:.3f}".format(x))

Solution: 61.800


Bereken alle gewichten in gram (vermenigvuldig ze dus met 1000) maar verander de tabel niet.  Geef het resultaat weer als een Python list.
Zie je wat er met de laatste waarde gebeurt?  Hoe komt dit?

In [426]:
result = (gegevens * 1000).values.tolist()
print(result, type(result))

[[1000.0, 15000.0, 54200.0, 36500.0], [2000.0, 16000.0, 68100.0, 37100.0], [4000.0, 18000.0, 59500.0, 37200.0], [5000.0, 19000.0, 65400.00000000001, 36900.0]] <class 'list'>


Zet alle temperaturen om naar Fahrenheit, rondt deze af op 1 cijfer na de komma en zet deze waarden in de tabel in een nieuwe kolom met de naam "temp_far".
Hint: een kolom uit een data frame is een Series en heeft een methode "round()"

In [427]:
gegevens['temp_far'] = (gegevens.temp * 1.8) + 32
print(gegevens)

   id  leeftijd  gewicht  temp  temp_far
0   1        15     54.2  36.5     97.70
1   2        16     68.1  37.1     98.78
3   4        18     59.5  37.2     98.96
4   5        19     65.4  36.9     98.42


Volgende code bewaart de tabel in een bestand "gegevens.csv".  Voer deze gewoon uit en kijk waar het bestand bewaard werd:

In [428]:
gegevens.to_csv("./data/gegevens.csv", sep=";", decimal=",", index=False)

Open de tabel in excel of open office. Als je het bestand juist bewaard hebt, zou dit moeten lukken.  Je kan het bestand eventueel ook uploaden naar google drive en openen met google spreadheets.
Voeg er een kolom aan toe met de naam "extra".  Zet volgende gegevens in de kolom: "hallo", "dit", "is", "een", "testje"
Bewaar het bestand als csv.

Lees de aangepaste tabel nu terug in met volgende code en kijk na of de nieuwe kolom goed werd ingelezen:

In [429]:
gegevens = pd.read_csv("./data/gegevens.csv", sep=";", decimal=",", header=0)
print(gegevens)

   id  leeftijd  gewicht  temp  temp_far
0   1        15     54.2  36.5     97.70
1   2        16     68.1  37.1     98.78
2   4        18     59.5  37.2     98.96
3   5        19     65.4  36.9     98.42


Verwijder de kolom “id”.

In [430]:
gegevens.drop(columns='id', inplace=True)

Voeg een rij toe met [ 30, 74.1, 36.5, 97.7 ] als waarden (zoek eens op hoe je dat kan doen)

In [431]:
new_row = [30, 74.1, 36.5, 97.7]
gegevens.loc[len(gegevens)] = new_row
print(gegevens)

   leeftijd  gewicht  temp  temp_far
0      15.0     54.2  36.5     97.70
1      16.0     68.1  37.1     98.78
2      18.0     59.5  37.2     98.96
3      19.0     65.4  36.9     98.42
4      30.0     74.1  36.5     97.70


Voeg een kolom “lengte” toe met gegevens: 160, 175, 162, 169, 179

In [432]:
new_column = [160, 175, 162, 169, 179]
gegevens['lengte'] = new_column
print(gegevens)

   leeftijd  gewicht  temp  temp_far  lengte
0      15.0     54.2  36.5     97.70     160
1      16.0     68.1  37.1     98.78     175
2      18.0     59.5  37.2     98.96     162
3      19.0     65.4  36.9     98.42     169
4      30.0     74.1  36.5     97.70     179


Bereken de BMI van iedere persoon in de tabel en rond deze af op 1 cijfer na de komma.
De BMI is gelijk aan het gewicht gedeeld door de lengte in het kwadraat.  De lengte moet in meter uitgedrukt zijn en het gewicht in kilogram.
Het resultaat moet een list zijn.

In [433]:
bmi = gegevens.gewicht / (gegevens.lengte / 100) ** 2
bmi = bmi.round(2).tolist()
print(bmi, type(bmi))

[21.17, 22.24, 22.67, 22.9, 23.13] <class 'list'>


Voeg deze BMI als kolom toe aan de tabel.

In [434]:
gegevens['bmi'] = bmi
print(gegevens)

   leeftijd  gewicht  temp  temp_far  lengte    bmi
0      15.0     54.2  36.5     97.70     160  21.17
1      16.0     68.1  37.1     98.78     175  22.24
2      18.0     59.5  37.2     98.96     162  22.67
3      19.0     65.4  36.9     98.42     169  22.90
4      30.0     74.1  36.5     97.70     179  23.13


Toon alle gewichten die kleiner of gelijk zijn aan 60 uit de kolom gewicht als een list.

In [435]:
print((gegevens.gewicht[gegevens.gewicht <= 60]).tolist())

[54.2, 59.5]


Vervang in de kolom leeftijd alle leeftijden groter of gelijk aan 18 door 19.
Krijg je een warning?  Je kan dit oplossen door gegevens.loc[] te gebruiken.

In [436]:
gegevens.loc[gegevens.leeftijd >= 18, 'leeftijd'] = 19
print(gegevens.leeftijd)

0    15.0
1    16.0
2    19.0
3    19.0
4    19.0
Name: leeftijd, dtype: float64


Vind alle temperaturen van de personen die ouder zijn dan 16 jaar.  Geef het resultaat weer als een numpy array.

In [437]:
print(np.array(gegevens.temp[gegevens.leeftijd > 16]))

[37.2 36.9 36.5]


## Sport data

Lees het bestand "sportData.csv" in met volgende code.
Toon alle kolommen van de tabel, samen met hun type.

In [438]:
sport = pd.read_csv("./data/sportData.csv", sep=";", decimal=",", header=0)


Hoeveel data-rijen zijn er in dit bestand?

In [439]:
print(len(sport.values))

75


Bepaal alle mogelijke waarden die in de kolom "sport" voorkomen.

In [440]:
print(sport.sport.unique())

['geen' 'basketbal' 'voetbal' 'klimmen' 'turnen' 'anders' 'zwemmen' 'judo'
 'fitness' nan]


Wat is het maximum van kolom "leeftijd"?

In [441]:
print(sport.leeftijd.max())

14


Wat is de som van alle waarden van kolom "keer per week" die groter zijn dan 1?

In [442]:
print("Som: ", sport['keer per week'][sport['keer per week'] > 1].sum())

Som:  97


Geef een lijst van alle sporten die beoefend worden door mensen die meer dan 3 keer per week sporten.  Geef het resultaat als een Series.

In [443]:
x = sport['uren per week']
y = pd.Series(x > 3)
var = pd.Series(sport.sport[y].unique())
print(var, type(var))

0      voetbal
1       turnen
2       anders
3      zwemmen
4      klimmen
5    basketbal
6         judo
7      fitness
dtype: object <class 'pandas.core.series.Series'>


## Programmeren

Hier staan een aantal programmeeropdrachten om gewoon te raken aan de syntax en mogelijkheden van Python. Het is bedoeld voor de studenten die ook geïnteresseerd zijn in het programmeren zelf.

### Dobbelsteen
Schrijf een programma dat 6000 keer met de dobbelsteen rolt en telt hoeveel keer iedere waarde voorkomt.  Probeer geen lussen te moeten schrijven.  Je kan dit doen door te starten met een numpy array van 6000 willekeurige getallen tussen 1 en 6.

Voorbeeld van de werking (dit kan afwijken omdat het willekeurige getallen zijn, maar alle getallen zouden rond de 1000 moeten liggen):

```{text}
Aantal enen: 1007
Aantal tweeën: 994
Aantal drieën: 1006
Aantal vieren: 995
Aantal vijven: 998
Aantal zessen: 1000
```

In [444]:
values = np.random.randint(low=1, high=7, size=6000)
counts = np.bincount(values)

for i in range(1, len(counts)):
    print(f"Aantal {i}'en:", counts[i])

Aantal 1'en: 998
Aantal 2'en: 956
Aantal 3'en: 970
Aantal 4'en: 1020
Aantal 5'en: 1004
Aantal 6'en: 1052


### Kerstboom

Schrijf een programma om een kerstboom af te drukken met behulp van ‘*’ tekens. De breedte van de boom wordt als een oneven geheel getal (13..29)  ingegeven. Indien niet voldaan is aan deze voorwaarde wordt de breedte op 13 ingesteld.

Eerst moet je het midden van de boom bepalen aan de hand van de breedte.
Vervolgens druk je de boom regel per regel af.
Opmerking: de stam bestaat altijd uit 4 regels met een breedte van 3.
Gebruik een for-lus om de boom af te drukken.

Je kan het getal inlezen met volgende code:
```{python}
breedte = int(input("Geef de breedte de van kerstboom (oneven getal in bereik 13..29):"))
```
Als je iets wil printen zonder newline op het einde (zoals System.out.print() in Java), dan kan dat als volgt:
```{python}
print("hello, ", end='')
print("world!")
```
Je kan een aantal keer hetzelfde karakter in een string zetten met:
```{python}
karakter = "*"
aantal = 5
print(karakter * aantal)
```

Voorbeeld van de werking:

```{text}
Geef de breedte de van kerstboom (oneven getal in bereik 13..29): 13

      *
     ***
    *****
   *******
  *********
 ***********
*************
     ***
     ***
     ***
     ***
```

In [445]:
breedte = int(input("Geef de breedte van de kerstboom (oneven getal in bereik 13..29):"))
breedte = max(13, min(29, breedte))
midden = breedte // 2

for i in range(midden + 1):
    print(('*' * (2 * i + 1)).center(breedte))

for _ in range(4):
    print('***'.center(breedte))

      *      
     ***     
    *****    
   *******   
  *********  
 *********** 
*************
     ***     
     ***     
     ***     
     ***     


### Geheim schrift
Schrijf een programma om berichten te coderen en te decoderen zoals Julius Caesar deed.
Het programma vraagt eerst een bericht.  Dit bericht wordt naar hoofdletters omgezet.
Daarna vraagt het programma aan de gebruiker of het bericht gecodeerd of gedecodeerd moet worden.
Om te coderen, doorloopt het programma alle letters in het bericht en verschuift deze letter telkens een aantal plaatsen (zet deze verschuiving in een variabele).
Met een verschuiving van 3 wordt bijvoorbeeld de letter 'A' een 'D'.  Indien je aan het einde van het alfabet komt begin je terug bij de 'A' (een 'Z' wordt in dit geval een 'C'). Bij het decoderen doe je uiteraard het tegenovergestelde.  Je kan dit heel snel doen door gebruik te maken van de ASCII code van ieder karakter (je mag ervan uitgaan dat alle karakters in de ASCII set passen).
Als een karakter geen letter is, dan wordt die gewoon ongecodeerd (of ongedecodeerd) weergegeven.

Voorbeeld van werking (de verschuiving staat hier op 6):
```{text}
Geef een bericht: The quick brown fox jumps over the lazy dog.
Wil je dit encoderen? J
Gecodeerd bericht:
ZNK WAOIQ HXUCT LUD PASVY UBKX ZNK RGFE JUM.

Geef een bericht: ZNK WAOIQ HXUCT LUD PASVY UBKX ZNK RGFE JUM.
Wil je dit encoderen? N
Gedecodeerd bericht:
THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG.
```
Hint: je kan de code heel compact maken als je gebruik maakt van de modulo (%) operator.
Hint: je kan een karakter omzetten naar zijn ASCII code met "ord(c)" en omgekeerd kan je een ASCII code naar een karakter omzetten met "chr(code)"

In [446]:
verschuiving = 6
bericht = input("Geef een bericht: ").upper()
encoderen = input("Wil je dit encoderen? ").upper() == 'J'

for c in bericht:
    if c.isalpha():
        c = chr((ord(c) - ord('A') + (verschuiving if encoderen else -verschuiving)) % 26 + ord('A'))
    print(c, end='')

ZXMZKXMUV?ZMKXZ

### Vervangen
Maak een functie "vervang(lijst, te_zoeken, vervanging)" die in een list op zoek gaat naar een waarde en die vervangt door een andere.

In [447]:
def vervang(lijst, te_zoeken, vervanging):
    for i in range(0, len(lijst)):
        if lijst[i] == te_zoeken:
            lijst[i] = vervanging

Test de functie uit door in de list [ 10, 20, 30, 30, 40, 30, 0 ] de waarde 30 te vervangen door 42.
Probeer of je functie ook werkt op een numpy array en een pandas Series.  Dat zou moeten lukken.

In [448]:
lijst = [10, 20, 30, 30, 40, 30, 0]
vervang(lijst, 30, 42)
print(lijst)
lijst2 = np.array([10, 20, 30, 30, 40, 30, 0])
vervang(lijst2, 30, 42)
print(lijst2)
lijst3 = pd.Series([10, 20, 30, 30, 40, 30, 0])
vervang(lijst3, 30, 42)
print(lijst3)

[10, 20, 42, 42, 40, 42, 0]
[10 20 42 42 40 42  0]
0    10
1    20
2    42
3    42
4    40
5    42
6     0
dtype: int64


### Wachtwoorden
Een goed wachtwoord kiezen, is voor sommige gebruikers een ware opgave.  We willen een programma maken waarin de gebruiker een nieuw wachtwoord moet kiezen.  Dit moet (omdat we het graag ingewikkeld maken) minstens 8 karakters lang zijn, minstens 1 hoofdletter, 1 kleine letter, een cijfer en een leesteken bevatten.
Maak een functie "is_goed_wachtwoord" die een wachtwoord als parameter meekrijgt en een boolean teruggeeft.  Die boolean is true als het gegeven wachtwoord voldoet aan alle eisen.  De functie geeft ook een foutmelding op het scherm als het wachtwoord niet goed is.
Maak dan een programma dat een nieuw wachtwoord vraagt totdat alle eisen voldaan zijn.

Voorbeeld van de werking:

```{text}
Geef een nieuw wachtwoord: ww
Het moet minstens 8 karakters lang zijn
Geef een nieuw wachtwoord: wachtwoord
Het moet minstens 1 hoofdletter bevatten
Geef een nieuw wachtwoord: WACHTWOORD
Het moet minstens 1 kleine letter bevatten
Geef een nieuw wachtwoord: Wachtwoord
Het moet minstens 1 cijfer bevatten
Geef een nieuw wachtwoord: Wachtw00rd
Het moet minstens 1 leesteken bevatten
Geef een nieuw wachtwoord: Wachtw00rd!
Je nieuwe wachtwoord is goedgekeurd!
```

Hint: je kan heel eenvoudig itereren door de karakters van een string met:
```{python}
for c in string:
    ...
```

In [449]:
def is_goed_wachtwoord(password):
    if len(password) < 8:
        print("Het moet minstens 8 karakters lang zijn")
        return False

    if not any(c.isupper() for c in password):
        print("Het moet minstens 1 hoofdletter bevatten")
        return False

    if not any(c.islower() for c in password):
        print("Het moet minstens 1 kleine letter bevatten")
        return False

    if not any(c.isdigit() for c in password):
        print("Het moet minstens 1 cijfer bevatten")
        return False

    if not any(c in ['.', ',', ';', ':', '?', '!'] for c in password):
        print("Het moet minstens 1 leesteken bevatten")
        return False

    return True


password = ''
while not is_goed_wachtwoord(password):
    password = input("Geef een nieuw wachtwoord: ")
print("Je nieuwe wachtwoord is goedgekeurd!")

Het moet minstens 8 karakters lang zijn
Het moet minstens 8 karakters lang zijn
Het moet minstens 8 karakters lang zijn
Het moet minstens 1 cijfer bevatten
Het moet minstens 1 cijfer bevatten
Het moet minstens 8 karakters lang zijn
Je nieuwe wachtwoord is goedgekeurd!
